"""Public-example map decomposition using only the current typed enumerator.

All operator/component/root attempts share one candidate and expansion budget.
The pointwise relation is a hypothesis, not a claim about unseen inputs; every
composed root must pass the complete original public examples. Independent
verification belongs to the caller. No task identities or private examples
are accessed.
"""
from __future__ import annotations

from dataclasses import dataclass, field
import time

from ..enumeration import enumerate_programs
from ..evaluator import evaluate
from ..terms import apply
from ..types import Arrow, function_parts
from .efficient_memory import _key


@dataclass
class SearchResult:
    term: object = None
    candidates: int = 0
    helper_attempts: int = 0
    head_attempts: int = 0
    component_attempts: int = 0
    root_attempts: int = 0
    example_evaluations: int = 0
    evaluator_steps: int = 0
    expansions: int = 0
    termination: str = "not_applicable"
    cpu_seconds: float = 0.0
    wall_seconds: float = 0.0
    trials: list = field(default_factory=list)
    decomposition: dict = field(default_factory=dict)


class _Stopped(Exception):
    def __init__(self, reason):
        self.reason = reason


class _MeteredGrammar:
    def __init__(self, grammar, result, check, max_expansions):
        self.grammar, self.result, self.check = grammar, result, check
        self.max_expansions = max_expansions

    def productions(self, *args, **kwargs):
        self.check()
        if self.result.expansions >= self.max_expansions:
            raise _Stopped("expansion_budget")
        self.result.expansions += 1
        choices = self.grammar.productions(*args, **kwargs)
        self.check()
        return choices


def _projection(examples, request_type, check):
    arguments, output = function_parts(request_type)
    if len(arguments) != 1 or arguments[0].tag != "list" or output.tag != "list":
        return None, "request_is_not_single_list_to_list"
    pairs, seen = [], {}
    for inputs, expected in examples:
        check()
        if len(inputs) != 1 or type(inputs[0]) is not list or type(expected) is not list:
            return None, "public_values_are_not_lists"
        if len(inputs[0]) != len(expected):
            return None, "length_mismatch"
        for value, target in zip(inputs[0], expected):
            check()
            key, target_key = _key(value), _key(target)
            if key in seen:
                if seen[key] != target_key:
                    return None, "inconsistent_pointwise_relation"
            else:
                seen[key] = target_key
                pairs.append(((value,), target))
    if not pairs:
        return None, "no_observed_elements"
    return (Arrow(arguments[0].args[0], output.args[0]), pairs), None


def solve_decomposition(examples, request_type, budget, grammar, *, max_size=12,
                        max_expansions=20000, step_budget=2000, max_cpu_seconds=10):
    """Return a public solution or an accounted partial diagnostic.

    A helper head is a one-node, type-compatible operator/library reference
    generated by the frozen enumerator. It is interpreted as a closed value and
    charged once. Every scalar component is interpreted on derived public
    examples, charged once, with every interpreter invocation counted. Each
    full-root verification costs another candidate attempt. Early mismatch is
    allowed; success requires all derived and original examples to pass.
    """
    started, wall = time.process_time(), time.perf_counter()
    result = SearchResult()
    examples = tuple(examples)
    if type(budget) is not int or budget < 0 or type(max_expansions) is not int or max_expansions < 0:
        raise ValueError("budgets require nonnegative integers")
    if max_cpu_seconds is not None and (type(max_cpu_seconds) not in (int, float) or max_cpu_seconds < 0):
        raise ValueError("CPU budget requires a nonnegative number or None")

    def check():
        if max_cpu_seconds is not None and time.process_time() - started >= max_cpu_seconds:
            raise _Stopped("cpu_budget")

    def attempt(term, cases, stage):
        check()
        if result.candidates >= budget:
            raise _Stopped("candidate_budget")
        result.candidates += 1
        if stage == "root":
            result.root_attempts += 1
        else:
            result.helper_attempts += 1
            if stage == "head":
                result.head_attempts += 1
            else:
                result.component_attempts += 1
        trial = {"index": result.candidates - 1, "stage": stage, "term": term.to_dict(),
                 "readable": str(term), "example_evaluations": 0, "evaluator_steps": 0,
                 "matched": False, "complete": False, "failure": None}
        result.trials.append(trial)
        for inputs, expected in cases:
            check()
            evaluated = evaluate(term, inputs, library=grammar.library, step_budget=step_budget)
            result.example_evaluations += 1
            result.evaluator_steps += evaluated.steps
            trial["example_evaluations"] += 1
            trial["evaluator_steps"] += evaluated.steps
            # The frozen evaluator bounds its own steps, not CPU time. Charge
            # a completed call even when it crosses our outer CPU deadline;
            # a late final match must not become an accepted solution.
            check()
            # A head is a closed callable value; its exact result is not used
            # as fitness or serialized. Its type comes from enumeration.
            matched = evaluated.ok and (stage == "head" or evaluated.value == expected)
            if not matched:
                trial["failure"] = evaluated.error or "public_output_mismatch"
                trial["complete"] = True
                return False
        check()
        trial["matched"] = trial["complete"] = True
        return True

    def generated(type_, size):
        remaining = max_expansions - result.expansions
        if remaining <= 0:
            raise _Stopped("expansion_budget")
        meter = _MeteredGrammar(grammar, result, check, max_expansions)
        for candidate in enumerate_programs(type_, meter, max_size=size, max_expansions=remaining):
            check()
            # Every complete pop is another expansion; partial pops were
            # charged in productions. There are no score callbacks/reinserts.
            if result.expansions >= max_expansions:
                raise _Stopped("expansion_budget")
            result.expansions += 1
            yield candidate.term

    try:
        check()
        projection, failure = _projection(examples, request_type, check)
        result.decomposition = {"kind": "pointwise_map", "supported": projection is not None,
                                "reason": failure, "public_examples": len(examples)}
        if projection is not None:
            component_type, scalar_examples = projection
            result.decomposition.update({"component_type": str(component_type),
                                         "component_examples": scalar_examples,
                                         "unique_elements": len(scalar_examples)})
            head_type = Arrow(component_type, request_type)
            heads = []
            for head in generated(head_type, 1):
                if attempt(head, (((), None),), "head"):
                    heads.append(head)
            if not heads:
                result.termination = ("expansion_budget" if result.expansions >= max_expansions
                                      else "no_compatible_head")
            elif max_size < 3:
                result.termination = "size_budget"
            else:
                result.termination = "component_stream_ended"
                for component in generated(component_type, max_size - 2):
                    if not attempt(component, scalar_examples, "component"):
                        continue
                    for head in heads:
                        root = apply(head, component)
                        if attempt(root, examples, "root"):
                            check()
                            result.term, result.termination = root, "public_solution"
                            return result
                if result.expansions >= max_expansions:
                    result.termination = "expansion_budget"
        check()
    except _Stopped as stopped:
        result.termination = stopped.reason
        if result.trials and not result.trials[-1]["complete"]:
            result.trials[-1]["failure"] = stopped.reason
    finally:
        result.cpu_seconds = time.process_time() - started
        result.wall_seconds = time.perf_counter() - wall
    return result


def search(task, grammar, budget=64, **limits):
    """Convenience adapter; reads only public examples and declared request type."""
    return solve_decomposition(task.examples, task.request_type, budget, grammar, **limits)
